In [3]:
import numpy as np
# 生成随机数组
data = np.random.randn(2, 3)
data

array([[-0.15630376, -0.51293777, -0.78035196],
       [ 0.64506571, -0.31505805, -2.01133844]])

In [2]:
data * 10

array([[-11.39681787,   7.55048101,   0.98231712],
       [ -5.89407683,  12.3236902 ,  -3.1392774 ]])

In [3]:
data + data

array([[-2.27936357,  1.5100962 ,  0.19646342],
       [-1.17881537,  2.46473804, -0.62785548]])

In [4]:
data.shape  # 表示数组每一维度的数量

(2, 3)

In [5]:
data.dtype  # 表示数组的数据类型

dtype('float64')

In [6]:
# 4.1.1 生成 ndarray
# 生成数组最简单的方式就是使用array函数。array函数接收任意的序列型对象
# （当然也包括其他的数组），生成一个新的包含传递数据的NumPy数组。
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
# 嵌套序列，例如同等长度的列表，将会自动转换程多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# 因为data2是一个包含列表的列表，
# 所以Numpy数组arr2形成了二维数组。
# 我们可以通过检查ndim和shape属性来确认这一点
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [12]:
"""
除非显式地指定，否则np.array会自动推断生成数组的数据类型。
数据类型被存储在一个特殊的元数据dtype中
"""
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

In [17]:
"""
除了np.array，还有很多其他函数可以创建新数组。
例如，给定长度及形状后，zeros可以一次性创造全0数组，
ones可以一次性创造全1数组。
empty则可以创建一个没有初始化数值的数组。
想要创建高维数组，则需要为shape传递一个元组
"""
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
"""
使用np.empty来生成一个全0数组，
并不安全，有些时候它可能会返回未初始化的垃圾数值。
"""
np.empty((2, 3, 2))

array([[[6.92562312e-310, 6.92562312e-310],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [7]:
# arange是 Python内建函数range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
"""
由于NumPy专注于数值计算，
如果没有特别指明的话，默认的数据类型是float64（浮点型）。
"""

'\n由于NumPy专注于数值计算，\n如果没有特别指明的话，默认的数据类型是float64（浮点型）。\n'

In [ ]:
# 4.1.2 ndarray的数据类型

In [26]:
"""
数据类型，即dytpe，是一个特殊的对象，
它包含了ndarray需要为某一种类型数据所申明的内存块信息
（也称为元数据，即表示数据的数据）
"""
arr3 = np.array([1, 2, 3], dtype=np.float64)  # 指定数据申明类型
arr4 = np.array([1, 2, 3], dtype=np.int32)

arr3.dtype

dtype('float64')

In [27]:
arr4.dtype

dtype('int32')

In [10]:
"""
可以使用astype方法显式地转换数组的数据类型
"""
arr5 = np.array([1, 2, 3, 4, 5])
arr5.dtype

dtype('int64')

In [11]:
float_arr = arr5.astype(np.float64)  # 转换数据类型
float_arr.dtype

dtype('float64')

In [12]:
"""
在上面例子中，整数被转换成了浮点数。
如果我把浮点数转换成整数，则小数点后的部分将被消除
"""
arr6 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr6

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [13]:
arr6.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [19]:
"""
如果你有一个数组，里面的元素都是表达数字含义的字符串，
也可以通过astype将字符串转换为数字
"""
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [20]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [16]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [36]:
"""
在NumPy中，当使用numpy.string_类型作字符串数据要小心，
因为NumPy会修正它的大小或删除输入且不发出警告。
pandas在处理非数值数据时有更直观的开箱型操作
"""

'\n在NumPy中，当使用numpy.string_类型作字符串数据要小心，\n因为NumPy会修正它的大小或删除输入且不发出警告。\npandas在处理非数值数据时有更直观的开箱型操作\n'

In [37]:
"""
数据类型的转换和指定，可以使用另一个数组的dtype属性
"""
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
"""
数据类型的转换和指定，也可以使用类型代码来传入数据类型
"""
empty_uint32 = np.empty(8, dtype='u4')  # u4 指定是4个字节，即 32 位
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [44]:
"""使用astype时总是生成一个新的数组，即使你传入的dtype与之前一样。"""
arr7 = np.arange(8)
arr8 = arr7.astype(arr7.dtype)
id(arr7) == id(arr8)

False

In [45]:
# 4.1.3 NumPy 数组算术

In [46]:
"""
数组之所以重要是因为它允许你进行批量操作而无须任何for循环。
NumPy用户称这种特性为向量化。
任何在两个等尺寸数组之间的算术操作都应用了逐元素操作的方式
"""
arr9 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr9

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr9 * arr9

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr9 - arr9

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
"""
带有标量计算的算术操作，会把计算参数传递给数组的每一个元素
"""
1 / arr9

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
arr9 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [51]:
"""同尺寸数组之间的比较，会产生一个布尔值数组"""
arr10 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr10

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [52]:
arr10 > arr9

array([[False,  True, False],
       [ True, False,  True]])

In [53]:
"""
不同尺寸的数组间的操作，将会用到广播特性，将会在附录A中介绍。
对于本书大部分内容来说，并不需要深入理解广播特性
"""

'\n不同尺寸的数组间的操作，将会用到广播特性，将会在附录A中介绍。\n对于本书大部分内容来说，并不需要深入理解广播特性\n'

In [54]:
# 4.1.4 基础索引与切片

In [55]:
"""
NumPy数组索引是一个大话题，
有很多种方式可以让你选中数据的子集或某个单个元素。
一维数组比较简单，看起来和Python的列表很类似
"""
arr11 = np.arange(10)
arr11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr11[5]

5

In [58]:
arr11[5:8]

array([5, 6, 7])

In [59]:
arr11[5:8] = 12
arr11

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [60]:
"""
如果你传入了一个数值给数组的切片，
例如arr[5:8]= 12，数值被传递给了整个切片。
区别于Python的内建列表，数组的切片是原数组的视图。
这意味着数据并不是被复制了，任何对于视图的修改都会反映到原数组上
"""
# 示例如下：
arr_slice = arr11[5:8]
arr_slice

array([12, 12, 12])

In [61]:
"""当我改变arr_slice，变化也会体现在原数组上"""
arr_slice[1] = 12345
arr11

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [62]:
"""
不写切片值的[:]将会引用数组的所有值
"""
arr_slice[:] = 64
arr11

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [64]:
"""
如果你还是想要一份数组切片的拷贝而不是一份视图的话，
你就必须显式地复制这个数组，例如arr[5:8].copy()
"""
arr_slice2 = arr11[5:8].copy()
arr_slice2[:] = 3
arr11  # 此时，可以看到，原arr11并未受到影响

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [66]:
"""
对更高维度的数组，你会有更多选择。在一个二维数组中，
每个索引值对应的元素不再是一个值，而是一个一维数组
"""
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [67]:
"""
以通过传递一个索引的逗号分隔列表去选择单个元素，以下两种方式效果一样
"""
arr2d[0][2]

3

In [68]:
arr2d[0, 2]

3

In [69]:
"""
在多维数组中，你可以省略后续索引值，返回的对象将是降低一个维度的数组
"""
arr3d = np.array([
                   [
                    [1, 2, 3],
                    [4, 5, 6]
                   ], 
                 [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
"""标量和数组都可以传递给arr3d[0]"""
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
"""类似地，arr3d[1, 0]返回的是一个一维数组"""
arr3d[1, 0]

array([7, 8, 9])

In [74]:
# 4.1.4.1 数组的切片索引

In [75]:
arr11

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [76]:
arr11[1:6]

array([ 1,  2,  3,  4, 64])

In [77]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
"""还可以进行多组切片，与多组索引类似"""
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [82]:
"""
当你像在上面这个例子中那样切片时，你需要按照原数组的维度进行切片。
如果将索引和切片混合，就可以得到低维度的切片。
例如，我可以选择第二行但是只选择前两列：
"""
arr2d[1, :2]

array([4, 5])

In [83]:
"""
类似地，我也可以选择第三列，但是只选择前两行：
"""
arr2d[:2, 2]

array([3, 6])

In [84]:
"""
需要注意的是，单独一个冒号表示选择整个轴上的数组，
因此你可以按照下面的方式在更高维度上进行切片
"""
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [85]:
"""
当然对切片表达式赋值时，整个切片都会重新赋值：
"""
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [86]:
# 4.1.5 布尔索引

In [22]:
"""
让我们考虑以下例子，假设我们的数据都在数组中，
并且数组中的数据是一些存在重复的人名。
我会使用numpy.random中的randn函数来生成一些随机正态分布的数据
"""
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [23]:
data

array([[-0.87706856,  1.34412374,  0.92822213, -0.86349498],
       [-1.08656897,  0.38696397, -0.88373758,  1.22428137],
       [ 1.83096243, -1.12117003,  1.84779824, -0.78628375],
       [-0.10667608, -1.46221394,  0.06366974,  0.54534431],
       [-0.2034624 ,  0.23626815, -0.67012084,  0.4705039 ],
       [-1.68370417, -0.21056032, -2.07429624, -2.47137386],
       [-0.41838135,  0.60682232,  0.06874396, -0.21815748]])

In [24]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [25]:
data[names == 'Bob']

array([[-0.87706856,  1.34412374,  0.92822213, -0.86349498],
       [-0.10667608, -1.46221394,  0.06366974,  0.54534431]])

In [27]:
data  # 可见，数组使用数学操作时并不会影响原本的值

array([[-0.87706856,  1.34412374,  0.92822213, -0.86349498],
       [-1.08656897,  0.38696397, -0.88373758,  1.22428137],
       [ 1.83096243, -1.12117003,  1.84779824, -0.78628375],
       [-0.10667608, -1.46221394,  0.06366974,  0.54534431],
       [-0.2034624 ,  0.23626815, -0.67012084,  0.4705039 ],
       [-1.68370417, -0.21056032, -2.07429624, -2.47137386],
       [-0.41838135,  0.60682232,  0.06874396, -0.21815748]])

In [28]:
data[names == 'Bob', 2:]  # 相当于切片索引

array([[ 0.92822213, -0.86349498],
       [ 0.06366974,  0.54534431]])

In [29]:
data[names == 'Bob', 3]

array([-0.86349498,  0.54534431])

In [30]:
"""
为了选择除了’Bob’以外的其他数据，
你可以使用！=或在条件表达式前使用～对条件取反
"""
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [34]:
data[(names == 'Bob')]

array([[-0.87706856,  1.34412374,  0.92822213, -0.86349498],
       [-0.10667608, -1.46221394,  0.06366974,  0.54534431]])

In [35]:
data[~(names == 'Bob')]

array([[-1.08656897,  0.38696397, -0.88373758,  1.22428137],
       [ 1.83096243, -1.12117003,  1.84779824, -0.78628375],
       [-0.2034624 ,  0.23626815, -0.67012084,  0.4705039 ],
       [-1.68370417, -0.21056032, -2.07429624, -2.47137386],
       [-0.41838135,  0.60682232,  0.06874396, -0.21815748]])

In [36]:
cond = names == 'Bob'
cond

array([ True, False, False,  True, False, False, False])

In [37]:
data[~cond]

array([[-1.08656897,  0.38696397, -0.88373758,  1.22428137],
       [ 1.83096243, -1.12117003,  1.84779824, -0.78628375],
       [-0.2034624 ,  0.23626815, -0.67012084,  0.4705039 ],
       [-1.68370417, -0.21056032, -2.07429624, -2.47137386],
       [-0.41838135,  0.60682232,  0.06874396, -0.21815748]])

In [38]:
"""
当要选择三个名字中的两个时，可以对多个布尔值条件进行联合，
需要使用数学操作符如&（and）和|（or）
"""
mask = (names == 'Bob') | (names == 'Will')  # 名称是 Bob 或者 Will
mask

array([ True, False,  True,  True,  True, False, False])

In [39]:
data[mask]

array([[-0.87706856,  1.34412374,  0.92822213, -0.86349498],
       [ 1.83096243, -1.12117003,  1.84779824, -0.78628375],
       [-0.10667608, -1.46221394,  0.06366974,  0.54534431],
       [-0.2034624 ,  0.23626815, -0.67012084,  0.4705039 ]])

In [40]:
"""
使用布尔值索引选择数据时，
总是生成数据的拷贝，即使返回的数组并没有任何变化

Python的关键字and和or对布尔值数组并没有用，
请使用&（and）和|（or）来代替。
"""

In [42]:
"""
基于常识来设置布尔值数组的值也是可行的。
将data中所有的负值设置为0，我们需要做
"""
data[data < 0] = 0
data

array([[0.        , 1.34412374, 0.92822213, 0.        ],
       [0.        , 0.38696397, 0.        , 1.22428137],
       [1.83096243, 0.        , 1.84779824, 0.        ],
       [0.        , 0.        , 0.06366974, 0.54534431],
       [0.        , 0.23626815, 0.        , 0.4705039 ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.60682232, 0.06874396, 0.        ]])

In [43]:
data[names != 'Joe']

array([[0.        , 1.34412374, 0.92822213, 0.        ],
       [1.83096243, 0.        , 1.84779824, 0.        ],
       [0.        , 0.        , 0.06366974, 0.54534431],
       [0.        , 0.23626815, 0.        , 0.4705039 ]])

In [45]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.38696397, 0.        , 1.22428137],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.60682232, 0.06874396, 0.        ]])

In [48]:
data > 0

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False,  True,  True, False]])

In [51]:
# 4.1.6 神奇索引
"""
神奇索引是NumPy中的术语，用于描述使用整数数组进行数据索引
"""
# 假设我们有一个 8 * 4 的数组
arr12 = np.empty((8, 4))
for i in range(8):
    arr12[i] = i
arr12

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [56]:
"""
为了选出一个符合特定顺序的子集，你可以简单地通过传递一个包
含指明所需顺序的列表或数组来完成
"""
arr12[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [57]:
"""
代码运行出你所想要的结果！如果使用负的索引，将从尾部进行选择
"""
arr12[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [59]:
"""
传递多个索引数组时情况有些许不同，
这样会根据每个索引元组对应的元素选出一个一维数组
"""
arr13 = np.arange(32).reshape((8, 4))
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
arr13[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [61]:
arr13[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [62]:
arr13[(1, 0)]

4

In [63]:
"""请牢记神奇索引与切片不同，它总是将数据复制到一个新的数组中"""
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [65]:
# 4.1.7  数组转置和换轴
"""
转置是一种特殊的数据重组形式，可以返回底层数据的视图而不需要复制任何内容。
数组拥有transpose方法，也有特殊的T属性
"""
arr14 = np.arange(15).reshape((3, 5))
arr14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr14.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [70]:
"""
我想起来python自带的zip函数，也可以用来进行数组的转换
"""
n = []
m = arr14.copy()
for i in zip(*m):
    n.append(list(i))
    print(i)
n

(0, 5, 10)
(1, 6, 11)
(2, 7, 12)
(3, 8, 13)
(4, 9, 14)


[[0, 5, 10], [1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14]]

In [71]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
"""
当进行矩阵计算时，你可能会经常进行一些特定操作，
比如，当计算矩阵内积会使用np.dot
"""
arr15 = np.random.randn(6, 3)
arr15

array([[ 0.23885823,  0.13178699, -0.23455261],
       [ 0.2530404 ,  0.20475519,  1.00374019],
       [ 0.68694989,  1.27989239, -0.45327191],
       [-0.10752979, -0.33898446, -0.23170764],
       [ 0.57911487,  0.79871363,  0.43463435],
       [-1.04745627,  0.33426901, -1.69504564]])

In [73]:
np.dot(arr15.T, arr15)

array([[ 2.03708418,  1.11137738,  1.93869178],
       [ 1.11137738,  2.56200673, -0.5464368 ],
       [ 1.93869178, -0.5464368 ,  4.38373989]])

In [76]:
# 自我示例
arr01_yezi = np.arange(1, 7).reshape(2, 3)
arr01_yezi

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr02_yezi = np.arange(1, 7).reshape(3, 2)
arr02_yezi

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
np.dot(arr01_yezi, arr02_yezi)  # 就是线性代数，计算矩阵内积

array([[22, 28],
       [49, 64]])

In [81]:
"""
对于更高维度的数组，transpose方法可以接收包含轴编号的元组，
用于置换轴（拓展下思维）
"""
arr16 = np.arange(16).reshape((2, 2, 4))
arr16

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [86]:
"""
# x, y,z轴本身对应 0， 1， 2.
transpose((1, 0, 2)) 即此时 x, y轴互换

比如： 数字 7 的坐标原先是(0, 1, 3)
       现在是(1, 0, 3)
"""
arr16.transpose((1, 0, 2))  

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [87]:
"""
上面那个看这个链接：
https://blog.csdn.net/qq_37377691/article/details/80086480
"""

'\n上面那个看这个链接：https://blog.csdn.net/qq_37377691/article/details/80086480\n'

In [88]:
arr16

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [89]:
"""
T进行转置是换轴的一个特殊案例。ndarray有一个swapaxes方法，
该方法接收一对轴编号作为参数，并对轴进行调整用于重组数据
如：数字1，(0, 0, 1) -->  (0, 1, 0)
"""

arr16.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])